sonar.projectKey=SolomiiaAndrusyshyn_lab5-digital-signature
sonar.organization=solomiiaandrusyshyn

sonar.sources=.

sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.test.js,lab3/**,lab4/**
sonar.cpd.exclusions=**/*.html,**/*.css,**/*.scss

sonar.projectVersion=2